<?php

namespace AppBundle\Entity\Doctrine\ORM;

/**
 * CollegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollegeRepository extends \Doctrine\ORM\EntityRepository
{
}
