<?php

namespace AppBundle\Doctrine\ORM;

use Doctrine\ORM\EntityRepository;

/**
 * ConventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConventionRepository extends EntityRepository
{
    public function findConventionsAvailables() {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT o
            FROM AppBundle:Convention o
            WHERE :today < o.endsAt
            ORDER BY o.endsAt DESC
        ')->setParameter('today', new \DateTime());

        return $consulta->getResult();
    }
}
